.Dd March 11, 2017
.Dt CUTHASH 1
.Sh NAME
.Nm cuthash
.Nd hash of selected items
.Sh SYNOPSIS
.Nm
.Op Fl s Ar separators
.Op Fl d Ar digest_algorithm
.Ar list
.Sh DESCRIPTION
.Nm
cuts a
.Ar list
of items separated by
.Ar separators
and computes hash to them.
The result hash is print to the standard output followed by first
.Ar separator
and followed by the input line.
Default separator is tabulator.
.Pp
.Ar list
is comma separated list of numbers and ranges starting from 1.
Ranges have the form 'M-N'.
Numbers and ranges may be repeated, overlapping and in any order.
.Pp
.Nm
allows to choose
.Ar digest_algorithm
from a set of digest algorithms provided by openssl.
See
.Xr dgst 1 .
.Sh BUGS
Please report them.
.Sh SEE ALSO
.Xr dgst 1 ,
.Xr openssl 1 ,
